- build/Dockerfile
- go.mod
Testing if this PR will trigger any jobs
> updating Dockerfile UBI version and labels

- Makefile
- build/Dockerfile.ppc64le
- build/Dockerfile.s390x
Updating Makefile changes to reflect multi-arch builds.
https://github.com/IBM/go-repo-template/blob/master/Makefile
> updating Makefile to latest version

- deploy/olm-catalog/ibm-auditlogging-operator/ibm-auditlogging-operator.package.yaml
Issue: https://github.com/IBM/ibm-auditlogging-operator/issues/8
> Update operator package name to match ODLM 

- deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/ibm-auditlogging-operator.v3.5.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/operator.ibm.com_auditloggings_crd.yaml
will push csv to quay after merge
> Newest csv

- pkg/resources/utils.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/36251
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/35470
> labels/annotations for metering/healthcheck

- pkg/resources/containers.go
we removed kube-audit last release, one occurrence was leftover
> remove kube-audit match

- deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/ibm-auditlogging-operator.v3.5.0.clusterserviceversion.yaml
- deploy/operator.yaml
- pkg/resources/utils.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/36553
> metering annotations

- deploy/olm-catalog/ibm-auditlogging-operator/ibm-auditlogging-operator.package.yaml
https://ibm-cloudplatform.slack.com/archives/CQU4MD7KM/p1585085830095700
> update csv channel

- deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml
- pkg/resources/containers.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/36714
> bump fluentd image version

- deploy/crds/operator.ibm.com_auditloggings_crd.yaml
- go.mod
- pkg/apis/operator/v1alpha1/auditlogging_types.go
- pkg/controller/auditlogging/auditlogging.go
- pkg/controller/auditlogging/auditlogging_controller.go
- pkg/resources/containers.go
- pkg/resources/utils.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/36715
> feat(core): add new in_http plugin

- pkg/controller/auditlogging/auditlogging.go
- pkg/controller/auditlogging/auditlogging_controller.go
- pkg/resources/containers.go
- pkg/resources/rbac.go
- pkg/resources/utils.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/36721
https://github.ibm.com/IBMPrivateCloud/roadmap/blob/master/feature-specs/common-services-2Q2020/operator-install/operand-service-account.md#implementation
> Create ibm-auditlogging-operand service account

- deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
https://github.com/IBM/operand-deployment-lifecycle-manager/blob/master/deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml#L835
> replaces field for olm

- deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
- deploy/role.yaml
```
JitterUntil\n\t/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
{"level":"error","ts":1586815090.8291426,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"auditlogging-controller","request":"/example-auditlogging","error":"clusterroles.rbac.authorization.k8s.io \"audit-policy-controller\" is forbidden: user \"system:serviceaccount:ibm-common-services:ibm-auditlogging-operator\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:ibm-common-services\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently …
```
> allow operator to grant restricted scc

- deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/36969
> manage operator dependency

- README.md
- deploy/crds/operator.ibm.com_auditloggings_crd.yaml
- deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml
- deploy/operator.yaml
> Cv lint 35747

- pkg/resources/containers.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/36963#workspaces/cloudpakicp-58eb8bceeaae55d225b7a0a7/board?labels=squad%3Asecurity-audit&repos=145464
Post:
```
➜  ibm-auditlogging-operator git:(qradar) ✗ k exec -it audit-log-test-7f874b8945-gz6rq bash
Defaulting container name to icp-audit-service.
Use 'kubectl describe pod/audit-log-test-7f874b8945-gz6rq -n ibm-common-services' to see all of the containers in this pod.
bash-4.2$ curl -i -X POST -d '{"typeURI":"http://schemas.dmtf.org/cloud/audit/1.0/event","eventType":"activity","id":"icp:999999-a9dd-11e8-817b-89bcae80625c","action":"read","requestPath":"/identity/api/v1/directory/ldap/56027bb0-a9dd-11e8-9573-0b442b44e932/fetchUsergroups?searchString=%2Ac%2A","initiator":{"typeURI":"service/security/account/user","name":"admin","cr …
```
> create message key in http log records for qradar

- pkg/controller/auditlogging/auditlogging.go
- pkg/resources/rbac.go
- pkg/resources/utils.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/37262
> fix policy controller upgrade

- deploy/crds/operator.ibm.com_auditloggings_crd.yaml
- pkg/apis/operator/v1alpha1/auditlogging_types.go
- pkg/controller/auditlogging/auditlogging.go
- pkg/resources/containers.go
- pkg/resources/utils.go
- Ensures default http port is used and not tampered with
- Change service update to delete (update is not allowed on service ports)
- Remove http port customization
> fix reconcile equals cases and remove port customization

- pkg/resources/utils.go
case requires affinity defined for operands...
e2e test completed:  SUCCESS: ALL records found in splunk.
> operands require affinity for case certification

- deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml
- deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
- pkg/controller/auditlogging/auditlogging.go
- pkg/controller/auditlogging/auditlogging_controller.go
- pkg/resources/containers.go
- pkg/resources/utils.go
- use default images for operands and ignore imageTag in CR
- update configmaps with new match tags for http logs
- delete old service accounts
> fix upgrade to 3.6.0

- build/Dockerfile
- build/Dockerfile.ppc64le
- build/Dockerfile.s390x
Not a psirt, but va-scans
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/37403
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/37463
https://ibm-cloudplatform.slack.com/archives/GBU53DH70/p1588024099056900
> update ubi images

- Makefile
- README.md
- deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml
- pkg/controller/auditlogging/auditlogging.go
- pkg/controller/auditlogging/auditlogging_controller_test.go
- pkg/resources/containers.go
- pkg/resources/utils.go
Keeps siem configs when updating output plugin configmaps
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/37640
> in place update for output plugin configmaps

- build/Dockerfile
- build/Dockerfile.ppc64le
- build/Dockerfile.s390x
- pkg/controller/auditlogging/auditlogging_controller_test.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/37670
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/37710
> updated ubi8 min images

- pkg/controller/auditlogging/auditlogging.go
- pkg/controller/auditlogging/auditlogging_controller_test.go
- pkg/resources/containers.go
- pkg/resources/utils.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/37640
> preserve output config on update

- Makefile
- common/scripts/get_image_sha.sh
- deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
- deploy/operator.yaml
- pkg/apis/operator/v1alpha1/auditlogging_types.go
- pkg/controller/auditlogging/auditlogging.go
- pkg/controller/auditlogging/auditlogging_controller_test.go
- pkg/resources/containers.go
- pkg/resources/utils.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/37380
> pull operand images by SHA instead of tag

- pkg/controller/auditlogging/auditlogging.go
- pkg/resources/utils.go
https://github.ibm.com/ibmprivatecloud/roadmap/issues/37947
> update logic for labels/annotations

- deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
```
E0514 18:35:01.288729       1 reconcile_operand.go:133] Failed to convert alm-examples in the subscription ibm-auditlogging-operator to slice: invalid character '"' after object key
E0514 18:35:01.288762       1 reconcile_operand.go:74] Failed to get create or update custom resource: invalid character '"' after object key
```
after fix:
```I0514 19:01:50.223158       1 operandrequest_controller.go:135] Reconciling OperandRequest audit in the namespace ibm-common-services
I0514 19:01:50.251920       1 operandrequest_controller.go:277] Add finializer to the OperandRequest audit in the namespace ibm-common-services
I0514 19:01:50.262036       1 reconcile_operator.go:39] Reconciling Operators
I0514 19:01:50.316761       1 reconcile_operator.go:149] Creating the Subscription: …
```
> colon missing in csv

- deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-auditlogging-operator/ibm-auditlogging-operator.package.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/38050
> update csv to beta channel

- .osdk-scorecard.yaml
- Makefile
- README.md
- common/scripts/create-bundle.sh
- deploy/olm-catalog/ibm-auditlogging-operator/3.6.1/ibm-auditlogging-operator.v3.6.1.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-auditlogging-operator/3.6.1/operator.ibm.com_auditloggings_crd.yaml
- deploy/olm-catalog/ibm-auditlogging-operator/ibm-auditlogging-operator.package.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/38050
> bump version to 3.6.1

- deploy/olm-catalog/ibm-auditlogging-operator/3.6.1/ibm-auditlogging-operator.v3.6.1.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-auditlogging-operator/ibm-auditlogging-operator.package.yaml
https://github.ibm.com/ibmprivatecloud/roadmap/issues/38344
> move 3.6.1 into beta channel

- Makefile
- README.md
- deploy/olm-catalog/ibm-auditlogging-operator/3.6.2/ibm-auditlogging-operator.v3.6.2.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-auditlogging-operator/3.6.2/operator.ibm.com_auditloggings_crd.yaml
- deploy/olm-catalog/ibm-auditlogging-operator/ibm-auditlogging-operator.package.yaml
- pkg/resources/containers.go
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/38446
> increase limits to meet needs on ppc64le

- deploy/olm-catalog/ibm-auditlogging-operator/3.6.2/ibm-auditlogging-operator.v3.6.2.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-auditlogging-operator/ibm-auditlogging-operator.package.yaml
https://github.ibm.com/ibmprivatecloud/roadmap/issues/38504
> move 3.6.2 into beta

- deploy/olm-catalog/ibm-auditlogging-operator/ibm-auditlogging-operator.package.yaml
https://github.ibm.com/ibmprivatecloud/roadmap/issues/38538
> move 3.6.2 to stable-v1

- Makefile
- README.md
- deploy/olm-catalog/ibm-auditlogging-operator/3.7.0/ibm-auditlogging-operator.v3.7.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-auditlogging-operator/3.7.0/operator.ibm.com_auditloggings_crd.yaml
- deploy/olm-catalog/ibm-auditlogging-operator/ibm-auditlogging-operator.package.yaml
- version/version.go
> bump version to 3.7.0

- README.md
- deploy/olm-catalog/ibm-auditlogging-operator/3.7.0/ibm-auditlogging-operator.v3.7.0.clusterserviceversion.yaml
- pkg/controller/auditlogging/auditlogging.go
- pkg/resources/configmaps.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/39256
> update e2e link/add ingest cm/add ingest cm  to bindinfo

- pkg/controller/commonaudit/commonaudit.go
- pkg/controller/commonaudit/commonaudit_controller.go
- pkg/controller/commonaudit/commonaudit_controller_test.go
- pkg/resources/deployments.go
- pkg/resources/secret.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/39669
> feat(resources): new audit-certs secret managed by operator

- Makefile
- build/Dockerfile.ppc64le
- build/Dockerfile.s390x
- common/scripts/config_docker.sh
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/40019
> ci(prow): push image to artifactory

- deploy/olm-catalog/ibm-auditlogging-operator/3.7.0/ibm-auditlogging-operator.v3.7.0.clusterserviceversion.yaml
- deploy/operator.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/38461
> chore(csv): remove productVersion

- README.md
- pkg/resources/configmaps_v1.go
- pkg/resources/configmaps_v1alpha1.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/39806
> fix(resources): add message key to syslog input

- README.md
- pkg/controller/commonaudit/commonaudit.go
- pkg/resources/deployments.go
- pkg/resources/secret.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/39669
> fix(resources): kube handles mounted secret update so remove sha for secret

- deploy/olm-catalog/ibm-auditlogging-operator/3.7.0/ibm-auditlogging-operator.v3.7.0.clusterserviceversion.yaml
- go.mod
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/40261
https://github.ibm.com/IBMPrivateCloud/audit-policy-controller/pull/40
> fix: update policy ctrl sha and operator go version for psirt

- deploy/olm-catalog/ibm-auditlogging-operator/3.7.0/ibm-auditlogging-operator.v3.7.0.clusterserviceversion.yaml
- deploy/role.yaml
- deploy/role_binding.yaml
- pkg/resources/configmaps_v1alpha1.go
- pkg/resources/rbac.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/40269
> fix(rbac): remove unused/redundant resources

- .gitignore
- deploy/olm-catalog/ibm-auditlogging-operator/3.7.1/ibm-auditlogging-operator.v3.7.1.clusterserviceversion.yaml
- deploy/operator.yaml
- pkg/controller/auditlogging/auditlogging_controller_test.go
- pkg/resources/containers.go
- pkg/resources/utils.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/40495
> fix: update fluentd sha for twistlock

- pkg/controller/auditlogging/auditlogging.go
https://www-03preprod.ibm.com/support/knowledgecenter/3Q_3.5.0/audit-logging/3.x.x/audit_policy_ctrl.html#audit-policy-config
> fix(controller): add warning if CR is used for policy controller configs

- README.md
- deploy/olm-catalog/ibm-auditlogging-operator/3.7.1/ibm-auditlogging-operator.v3.7.1.clusterserviceversion.yaml
- deploy/operator.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/40647
> fix: policy ctrl resources

- build/Dockerfile
- build/Dockerfile.ppc64le
- build/Dockerfile.s390x
- deploy/olm-catalog/ibm-auditlogging-operator/3.7.1/ibm-auditlogging-operator.v3.7.1.clusterserviceversion.yaml
- deploy/operator.yaml
https://github.ibm.com/ibmprivatecloud/roadmap/issues/41004
> fix: update ubi image and operand shas

- deploy/olm-catalog/ibm-auditlogging-operator/3.7.1/ibm-auditlogging-operator.v3.7.1.clusterserviceversion.yaml
- deploy/operator.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/40135
> ci: update operator sha for beta2

- Makefile
remove multiarch bundle to fix prow build
> fix(cicd): remove multiarch bundle recipe

- Makefile
Wait for https://github.com/IBM/test-infra/pull/254 to first be merged
> fix(cicid): add cert crds to coverage

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42407
> fix(csv): add operandbindinfo

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- controllers/constant/constants.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42440
> fix: update policy ctrl sha

- config/manager/manager.yaml
https://github.ibm.com/IBMPrivateCloud/ibm-auditlogging-operator-case/pull/18
> fix: remove indent in env vars

- config/manager/manager.yaml
https://github.ibm.com/IBMPrivateCloud/ibm-auditlogging-operator-case/pull/18
> fix(config): fix manager yaml

- Makefile
- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42645
> fix(cicd): add GOARCH to build targets

- Makefile
Fixing multiarch build failure.
> removing extra slash from power build

- Dockerfile
- Dockerfile.ppc64le
- Dockerfile.s390x
- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/43390
> fix(dockerfile): update to ubi8 min 3-230

- Dockerfile
- Dockerfile.ppc64le
- Dockerfile.s390x
- Makefile
- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- common/util/namespace_scope.yaml
- common/util/operator_group.yaml
- controllers/auditlogging_controller.go
- controllers/auditlogging_controller_test.go
- controllers/commonaudit_controller.go
- controllers/commonaudit_controller_test.go
- controllers/constant/constants.go
- controllers/k8sutil/cache.go
- controllers/suite_test.go
- controllers/testutil/test_data.go
- controllers/util/utils.go
- controllers/util/utils_test.go
- hack/boilerplate.go.txt
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/43349
> fix(core): remove hardcoded ibm-common-services in GetCSNamespace

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/43651
> chore(cicd): bump Y version for 1Q2021

- Dockerfile.ppc64le
- Dockerfile.s390x
- Makefile
- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- common/Makefile.common.mk
- common/config/.hadolint.yml
- config/manager/manager.yaml
- controllers/resources/deployments.go
- controllers/resources/job.go
Changed image labels on two files.
> image labels changed

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/49648
> audit OperandRequest is not installing ibm-cert-manager-operator

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51185
> bump version for CS 3.15.0

- api/v1alpha1/auditlogging_types.go
- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- bundle/manifests/operator.ibm.com_auditloggings.yaml
- config/crd/bases/operator.ibm.com_auditloggings.yaml
- config/rbac/role.yaml
- config/samples/operator_v1alpha1_auditlogging.yaml
- controllers/auditlogging_controller.go
- controllers/commonaudit_controller.go
- controllers/reconcile_auditlogging.go
- controllers/reconcile_commonaudit.go
- controllers/resources/configmaps_v1alpha1.go
- controllers/resources/containers.go
- controllers/resources/deployments.go
- controllers/resources/job.go
- controllers/resources/rbac.go
- controllers/util/utils.go
- controllers/util/utils_test.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51298
> remove systemd source to remove privileged access #51298

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51538
> fix cv linter error

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51968
> version bump for CS 3.16.0 #51968

- controllers/resources/deployments.go
- controllers/util/utils.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/52190
> Fix for fluentd pod restart #52190

- controllers/reconcile_auditlogging.go
- controllers/reconcile_commonaudit.go
- controllers/resources/deployments.go
- controllers/util/utils.go
- controllers/util/utils_test.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/52190
> fix for fluentd restarts

- Dockerfile
- Dockerfile.ppc64le
- Dockerfile.s390x
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/52301
> Go version updated to 1.17.7 #52301

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/52607
> version bump up for CS 3.17.0 #52607

- Dockerfile
- Dockerfile.ppc64le
- Dockerfile.s390x
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/52579
> go version updated to resolve twistlock issue #52579

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53055
> version bumpup for CS 3.18.0 #53055

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- common/config/.hadolint.yml
- config/manager/manager.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53264
> movement to icr.io

- Dockerfile
- Dockerfile.ppc64le
- Dockerfile.s390x
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53484
> go version updated to resolve twistlock issue #53484

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54637
> Audit logging version bump for LTSR 3.19.4release #54637

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54638
> Audit logging version bump for CS 2.21.0 CD release #54638

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54895
> Update operand & operator version in monitoring operator  for LTSR 3.19.5 #54895

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54895
> Updated operand version for audit logging operator LTSR 3.19.5  #54895

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55207
> Operator and operand version bumpup  audit logging cs cd 3.22.0 

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55401
> Update operand & operator version in monitoring operator for LTSR 3.19.6

- Dockerfile
- Dockerfile.ppc64le
- Dockerfile.s390x
- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55207
> Update operand version for 3.22.0 and updated go version to 1.18.8

- Dockerfile
- Dockerfile.ppc64le
- Dockerfile.s390x
- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55874
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55268
> Update operand version for 3.19.7 and updated go version to 1.18.8

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55874
> Audit logging operand version bumup for 3.19.7

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56048
> Operator and operand version bumpup audit logging cs cd 3.23.0

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56330
> Operand and operator  version update  for Audit Logging 3.19.8  #56330

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56048
> Operand version update  for Audit Logging 3.23.0  #56048

- Dockerfile
- Dockerfile.ppc64le
- Dockerfile.s390x
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56110
> Go version updated to 1.19.4 #56110

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56330
> operand and operator version bumup for 3.24.0 #56851

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56330
> operand version bumup in operator for 3.19.8 #56330

- Dockerfile
- Dockerfile.ppc64le
- Dockerfile.s390x
- Makefile
- common/scripts/config_docker.sh
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56863
> Artifactory image location updated for audit logging #56863

- bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56851
> operand version bumpup for auditlogging 3.23.1 #56851
