IBM/ibm-auditlogging-operator

pkg/controller/auditlogging/auditlogging.go, pkg/resources/containers.go, pkg/resources/utils.go, version/version.go
Testing:
```
Name:           audit-logging-fluentd-ds
Selector:       app=fluentd,auditlogging_cr=example-auditlogging,component=auditlogging_svc
Node-Selector:  <none>
Labels:         app=fluentd
app.kubernetes.io/component=auditlogging_svc
app.kubernetes.io/instance=auditlogging
app.kubernetes.io/managed-by=operator
app.kubernetes.io/name=fluentd
release=auditlogging
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 3
Current Number of Nodes Scheduled: 3
Number of Nodes Scheduled with Up-to-date Pods: 3
Number of Nodes Scheduled with Available Pods: 3
Number of Nodes Misscheduled: 0
Pods Status:  3 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
Labels:           app=fluentd
app.kubernetes.io/component=auditlogging_svc …
```
=> add verbose labels

deploy/crds/operator.ibm.com_auditloggings_crd.yaml, pkg/apis/operator/v1alpha1/auditlogging_types.go, pkg/resources/utils.go
- user could have not set instanceNamespace and operator would break
- enabled will always default to false and we dont require user to set it at creation unless they want to
=> instanceNamespace cannot be empty, but enabled can be empty

Makefile, common/Makefile.common.mk, pkg/controller/auditlogging/auditlogging_controller.go, pkg/resources/containers.go
linter was complaining about the long lines in the fluentd cm
testing uncommenting qradar output plugin:
```
➜  ibm-auditlogging-operator git:(lint) ✗ k describe cm audit-logging-fluentd-ds-config
Name:         audit-logging-fluentd-ds-config
Namespace:    ibm-common-services
Labels:       app=fluentd
auditlogging_cr=example-auditlogging
Annotations:  <none>
Data
====
ENABLE_AUDIT_LOGGING_FORWARDING:
----
true
fluent.conf:
----
@include /fluentd/etc/source.conf
@include /fluentd/etc/remoteSyslog.conf
#@include /fluentd/etc/splunkHEC.conf
Events:  <none>
➜  ibm-auditlogging-operator git:(lint) ✗ k logs audit-logging-fluentd-ds-qvbdz
2020-03-05 20:51:01 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2020-03-05 20:51:01 +0000 [info]: using configuration file: …
```
=> remove long comments in cm

build/Dockerfile.ppc64le, build/Dockerfile.s390x
We were using the amd UBI image for s390 and ppc64le.
=> using correct ubi arch image for z and power

pkg/resources/containers.go
https://github.ibm.com/IBMPrivateCloud/audit-logging-chart/blob/master/stable/audit-logging/templates/audit-policy-controller-deployment.yaml#L71
```
➜  ibm-auditlogging-operator git:(resources) ✗ k describe deploy audit-policy-controller
Name:                   audit-policy-controller
Namespace:              ibm-common-services
CreationTimestamp:      Tue, 17 Mar 2020 10:58:17 -0500
Labels:                 app=audit-policy-controller
app.kubernetes.io/component=common-audit-logging
app.kubernetes.io/instance=common-audit-logging
app.kubernetes.io/managed-by=operator
app.kubernetes.io/name=audit-policy-controller
release=common-audit-logging
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=audit-policy-controller,auditlogging_cr=example-auditlogging, …
```
=> missing policy controller resources

deploy/crds/operator.ibm.com_auditloggings_crd.yaml, deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml, deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/ibm-auditlogging-operator.v3.5.0.clusterserviceversion.yaml, deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/operator.ibm.com_auditloggings_crd.yaml, pkg/apis/operator/v1alpha1/auditlogging_types.go, pkg/resources/utils.go
- audit policy controller doesnt use `default-duration`
- operator doesnt use `operatorVersion` for any logic
```
docker run -it hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com/ibmcom/audit-policy-controller-amd64:3.3.1 --default-duration=5 bash
flag provided but not defined: -default-duration
Usage of /usr/bin/audit-policy-controller:
-alsologtostderr
log to standard error as well as files
-cluster-name string
Name of the cluster (default "mcm-managed-cluster")
-kubeconfig string
Paths to a kubeconfig. Only required if out-of-cluster.
-log_backtrace_at value
when logging hits line file:N, emit a stack trace
-log_dir string
If non-empty, write log files in this directory
-logtostderr
log to standard error instead of files
-master string
The address of the Kubernetes …
```
=> remove unused args 

README.md
In the Documentation section, the link to KC was not coded.
=> updated KC link

deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml, deploy/operator.yaml, pkg/resources/containers.go, pkg/resources/rbac.go, pkg/resources/utils.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/36804
```
k describe po audit-policy-controller-59ff5646c5-5s5mx
Name:           audit-policy-controller-59ff5646c5-5s5mx
Namespace:      ibm-common-services
Priority:       0
Node:           worker1.audit-op.os.fyre.ibm.com/10.26.8.130
Start Time:     Mon, 13 Apr 2020 10:28:42 -0500
Labels:         app=audit-policy-controller
app.kubernetes.io/component=common-audit-logging
app.kubernetes.io/instance=common-audit-logging
app.kubernetes.io/managed-by=operator
app.kubernetes.io/name=audit-policy-controller
auditlogging_cr=example-auditlogging
component=common-audit-logging
pod-template-hash=59ff5646c5
release=common-audit-logging
Annotations:    k8s.v1.cni.cncf.io/networks-status:
[{
"name": "openshift-sdn",
"interface": "eth0",
"ips": …
```
=> run policy controller and operator as restricted

pkg/resources/containers.go
There was a bug where the output conf would only match to one `icp-audit.**` being the systemd logs with `icp-audit`. In order to match both, the config needed to be changed to `match icp-audit icp-audit.**` 
https://github.ibm.com/PrivateCloud-analytics/audit-logging/blob/3.0.0.0/fluent_source.conf#L45
=> fix matches bug

pkg/resources/utils.go
```
E0422 18:44:07.577519       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 1400 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1561de0, 0xc000656180)
/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1561de0, 0xc000656180)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/ibm/ibm-auditlogging-operator/pkg/resources.EqualSourceConfig(0xc00016c780, 0xc00016ca00, 0x26, 0x164d401, 0x13, 0x16643d5) …
```
=> fix index out of bounds for empty match

deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml, deploy/operator.yaml
Operator crashed with OOMKilled
Operator logs:
```
I0423 20:59:31.495514       1 trace.go:116] Trace[460128162]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96 (started: 2020-04-23 20:59:20.18622459 +0000 UTC m=+14.398729994) (total time: 11.307298567s):
Trace[460128162]: [11.306179337s] [11.306179337s] Objects listed
```
https://github.com/openshift/ocs-operator/blob/master/vendor/k8s.io/client-go/tools/cache/reflector.go#L157
=> up resources and update csv

pkg/controller/auditlogging/auditlogging.go, pkg/controller/auditlogging/auditlogging_controller.go, pkg/resources/utils.go
Reconcile cases where a resource was not equal would spit out the full specs in a log. Cleaned up not-equals logs and renamed reconcile methods
=> fix naming conventions/logs

Makefile
prow build fails on codecov step since it tries to run e2e tests without a kubeconfig
```
FAIL	github.com/ibm/ibm-auditlogging-operator/test/e2e	0.113s
FAIL
time="2020-04-27T13:56:24Z" level=fatal msg="Failed to create framework: failed to build the kubeconfig: invalid configuration: no configuration has been provided"
FAIL	github.com/ibm/ibm-auditlogging-operator/test/e2e	0.052s
FAIL
time="2020-04-27T13:56:29Z" level=fatal msg="Failed to create framework: failed to build the kubeconfig: invalid configuration: no configuration has been provided"
FAIL	github.com/ibm/ibm-auditlogging-operator/test/e2e	0.138s
FAIL
time="2020-04-27T13:56:34Z" level=fatal msg="Failed to create framework: failed to build the kubeconfig: invalid configuration: no configuration has been provided"
FAIL …
```
=> codecov only unit tests

deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml, deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml, pkg/controller/auditlogging/auditlogging.go
For this release (3.6.0) the default is
```
apiVersion: operator.ibm.com/v1alpha1
kind: AuditLogging
metadata:
name: example-auditlogging
spec:
fluentd:
enabled: false
imageRegistry: quay.io/opencloudio/
pullPolicy: IfNotPresent
journalPath: /run/log/journal
policyController:
imageRegistry: quay.io/opencloudio/
pullPolicy: IfNotPresent
verbosity: "0"
```
These defaults are the same if a customer does not define these fields
=> fix defaults to match doc

pkg/controller/auditlogging/auditlogging.go, pkg/controller/auditlogging/auditlogging_controller_test.go
Status was updating every reconcile loop because DeepEqual would return false if two slices with the same elements had different orders
Ex:
```{"level":"info","ts":1589402004.227247,"logger":"controller_auditlogging","msg":"Reconciling AuditLogging","Request.Namespace":"","Request.Name":"example-auditlogging"}
{"level":"info","ts":1589402004.2284575,"logger":"controller_auditlogging","msg":"Updating Audit Logging status","Namespace":"ibm-common-services","Name":"example-auditlogging","Name":"example-auditlogging"}
{"level":"info","ts":1589402004.2466183,"logger":"controller_auditlogging","msg":"Reconciliation successful!","Request.Namespace":"","Request.Name":"example-auditlogging","Name":"example-auditlogging"}
{"level":"info","ts":1589402009.2469664,"logger":"controller_auditlogging","ms …
```
=> fix update status

deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml, deploy/operator.yaml, test/e2e/auditlogging_test.go
- ran `make get-all-image-sha` and added to csv
- linter threw this error `test/e2e/auditlogging_test.go:21:2: ST1019: package "github.com/operator-framework/operator-sdk/pkg/test" is being imported more than once (stylecheck)` so fix added to this pr as well
=> update csv with operands sha

pkg/controller/auditlogging/auditlogging.go, pkg/controller/auditlogging/auditlogging_controller_test.go
In a op2op upgrade, if a user added hostaliases in 3.5 and upgrades to 3.6.x, the daemonset spec is updated, but hostaliases were not saved
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/37016
=> fix in place upgrade with hostaliases

go.mod, go.sum, pkg/controller/auditlogging/auditlogging_controller.go, pkg/controller/auditlogging/auditlogging_controller_test.go, pkg/controller/commonaudit/commonaudit_controller.go, pkg/controller/commonaudit/commonaudit_controller_test.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/39773
`oc delete auditlogging example-auditlogging`
and then
created commonaudit in ibm-common-services
and then
`kubectl apply -f deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml -n ibm-common-services`
and now i have
```
lauriet@Lauries-MacBook-Pro-1 audit-logging-bats % oc get pods | grep audit
audit-log-test-57cccff668-rbnbm                          1/1     Running     0          20m
audit-logging-fluentd-66cb54b6fd-pdvhq                   1/1     Running     0          23m
audit-logging-fluentd-ds-2vmrf                           1/1     Running     0          116s
audit-logging-fluentd-ds-qzd8q                           1/1     Running     0          116s
audit-logging-fluentd-ds-szwsn                           1/1 …
```
=> fix(controller): don't allow auditlogging to run with commonaudit

deploy/olm-catalog/ibm-auditlogging-operator/3.7.0/ibm-auditlogging-operator.v3.7.0.clusterserviceversion.yaml, deploy/operator.yaml
Note: These operand images do not exist in quay. For testing and development you can manually change the operand repos to integration in the CR and CSV or follow this doc https://github.ibm.com/IBMPrivateCloud/ibm-common-service-catalog
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/40147
=> fix(csv): use sha for operands

pkg/resources/deployments.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/40918
3 workers
scale replicas from 1 to 3:
```
➜  Desktop oc get po -o wide -w | grep audit
audit-logging-fluentd-5dcfd6975d-2cfhg             1/1     Running     0          40s     10.254.12.179   worker0.mykonos.os.fyre.ibm.com   <none>           <none>
audit-logging-fluentd-5dcfd6975d-ml48q             1/1     Running     0          40s     10.254.1.5      worker1.mykonos.os.fyre.ibm.com   <none>           <none>
audit-logging-fluentd-5dcfd6975d-r6d27             1/1     Running     0          39s     10.254.8.244    worker2.mykonos.os.fyre.ibm.com   <none>           <none>
```
scale replicas from 3 to 5
```
➜  Desktop oc get po -o wide | grep audit
audit-logging-fluentd-5dcfd6975d-2cfhg             1/1     Running     0 …
```
=> fix(HA): add PodAntiAffinity

controllers/util/utils.go, controllers/util/utils_test.go
```
2020-11-05T21:23:02.885Z	INFO	controller_auditlogging	Labels not equal	{"func": "EqualLabels", "Found": {"app":"fluentd","app.kubernetes.io/component":"common-audit-logging","app.kubernetes.io/instance":"common-audit-logging","app.kubernetes.io/managed-by":"operator","app.kubernetes.io/name":"fluentd","release":"common-audit-logging"}, "Expected": {"app":"fluentd","app.kubernetes.io/component":"common-audit-logging","app.kubernetes.io/instance":"common-audit-logging","app.kubernetes.io/managed-by":"operator","app.kubernetes.io/name":"fluentd","operator.ibm.com/managedBy-audit":"fluentd","release":"common-audit-logging"}}
2020-11-05T21:23:02.904Z	ERROR	controllers.AuditLogging	Failed to update Daemonset	{"Namespace": "ibm-common-services", "Name": "audit-logging-fluentd-ds", "error": …
```
=> fix(upgrade): labelselector is immutable after creation

Dockerfile, Dockerfile.ppc64le, Dockerfile.s390x, Makefile
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/43584
```
➜  ibm-auditlogging-operator git:(hbradfield-43584) ✗ make build-image-ppc64le
Setting /usr/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /usr/bin/qemu-arm-static as binfmt interpreter for arm
Setting /usr/bin/qemu-armeb-static as binfmt interpreter for armeb
Setting /usr/bin/qemu-sparc-static as binfmt interpreter for sparc
Setting /usr/bin/qemu-sparc32plus-static as binfmt interpreter for sparc32plus
Setting /usr/bin/qemu-sparc64-static as binfmt interpreter for sparc64
Setting /usr/bin/qemu-ppc-static as binfmt interpreter for ppc
Setting /usr/bin/qemu-ppc64-static as binfmt interpreter for ppc64
Setting /usr/bin/qemu-ppc64le-static as binfmt interpreter for ppc64le
Setting /usr/bin/qemu-m68k-static as …
```
=> fix(cicd): use arch specific base image

Dockerfile.ppc64le, Dockerfile.s390x, bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml, config/manager/manager.yaml, version/version.go
Remove the ` --progress=dot:giga` parameter that is currently causing prow builds to break
Additionally, fix up version number to 3.10.0
=> Fix prow build break and version number
